---
development:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/mediawatch_development?parseTime=true&multiStatements=true"}}

test:
  #
  # You can use a single URL string for the same configuration:
  #
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/mediawatch_test?parseTime=true&multiStatements=true&readTimeout=3s"}}
  #
  # Note that if you use `url`, other configurations are silently ignored.
  # In this case, the URL must contain all required connection parameters.
  #

production:
  #
  # You can also use environmental variables to override values in this config.
  #
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/mediawatch_production?parseTime=true&multiStatements=true&readTimeout=3s"}}

  #
  # And you can also override connection parameters by setting it under options.
  #
  #options:
  #  parseTime: true
  #  multiStatements: true
  #  readTimeout: 3s
  #  collation: "utf8mb4_general_ci"
  #
  # CAUTION!
  #   `parseTime` and` multiStatements` must be set to `true` to work properly.
  #   If you are not sure, do not change (or set) these values.
